rabbitmq/rabbitmq-web-stomp

src/rabbit_ws_sockjs.erl
test/src/rabbit_ws_test_raw_websocket.erl

Part of the rabbitmq/rabbitmq-web-stomp#13 work.

Update Cowboy to 1.0.3

---

src/rabbit_ws_handler.erl
src/rabbit_ws_sockjs.erl
test/src/rabbit_ws_test_cowboy_websocket.erl
test/src/rabbit_ws_test_raw_websocket.erl

DO NOT MERGE BEFORE #16 IS MERGED.
This is the first step documented in #17.

Add /ws route for STOMP over plain Cowboy Websocket

---

src/rabbit_ws_sockjs.erl
src/rabbitmq_web_stomp.app.src

Ticket #22.
Related to #2 and #21.
Also see doc changes at https://github.com/rabbitmq/rabbitmq-website/pull/69

Add options for TCP and Cowboy

---

src/rabbit_ws_handler.erl
src/rabbit_ws_sockjs.erl
src/rabbitmq_web_stomp.app.src
test/src/rabbit_ws_test_all.erl
test/src/rabbit_ws_test_cowboy_websocket.erl
test/src/rfc6455_client.erl

Add ws_frame option to enable binary frames

---

src/rabbit_ws_client.erl
src/rabbit_ws_client_sup.erl

Fixes #30 
@essen can you check please if everything is OK with termination?

Refactoring to compatibility with rabbitmq/rabbitmq-stomp/pull/51

---

src/rabbit_ws_client.erl

Properly report SSL connections

---

Makefile
rabbitmq-components.mk
src/rabbit_ws_sockjs.erl
src/rabbitmq_web_stomp.app.src

See https://github.com/rabbitmq/rabbitmq-web-stomp/issues/34

Change the default number of acceptors to 1

---

src/rabbit_ws_sockjs.erl

Honor cowboy_opts with SSL connections too

---

src/rabbit_ws_client.erl

Part of rabbitmq/rabbitmq-stomp#55
To be merged with rabbitmq/rabbitmq-stomp#60

Fill most management UI infos

---

src/rabbit_ws_client.erl

Fixes #48
Support for https://github.com/rabbitmq/rabbitmq-stomp/pull/73

Changes in heartbeat management

---

priv/schema/rabbitmq_web_stomp.schema

Schema for https://github.com/rabbitmq/rabbitmq-server/issues/550.

Cuttlefish schema

---

src/rabbitmq_web_stomp.app.src

Related to https://github.com/rabbitmq/rabbitmq-server/pull/776
Part of https://github.com/rabbitmq/rabbitmq-server/issues/735

Stub for broker_version_requirements

---

src/rabbit_ws_sockjs.erl

Fix for https://github.com/rabbitmq/rabbitmq-web-stomp/issues/65

Register listeners to management UI

---

src/rabbit_ws_sockjs.erl

Fixes #72 (or at least works around it).

Handle the case where Cowboy HTTP listener is already started.

---

test/amqp_stomp_SUITE.erl
test/cowboy_websocket_SUITE.erl
test/raw_websocket_SUITE.erl
test/sockjs_websocket_SUITE.erl

Related to rabbitmq/rabbitmq-stomp#112 and rabbitmq/rabbitmq-stomp#113

Add tests to demonstrate custom header usage

---

Makefile
priv/schema/rabbitmq_web_stomp.schema
src/rabbit_ws_listener.erl
test/config_schema_SUITE_data/rabbitmq_web_stomp.snippets

Add listener option to cuttlefish schema

---

priv/schema/rabbitmq_web_stomp.schema
src/rabbit_ws_listener.erl
test/config_schema_SUITE_data/rabbitmq_web_stomp.snippets

Closes #86, inspired by rabbitmq/rabbitmq-web-mqtt#30.

Make WebSocket endpoint configurable

---

src/rabbit_ws_handler.erl
src/rabbit_ws_listener.erl
test/proxy_protocol_SUITE.erl
test/src/rfc6455_client.erl

https://github.com/rabbitmq/rabbitmq-web-stomp/issues/84
The set of PRs in https://github.com/rabbitmq/rabbitmq-common/pull/279/files should be merged first.

Add PROXY protocol support

---

Makefile
priv/schema/rabbitmq_web_stomp.schema
test/config_schema_SUITE_data/rabbitmq_web_stomp.snippets

Per discussion with @acogoluegnes. Follow-up to #98.

New style config: support proxy protocol

---

src/rabbit_ws_handler.erl

Close STOMP connection on termination

---

priv/schema/rabbitmq_web_stomp.schema
src/rabbit_ws_listener.erl
test/config_schema_SUITE_data/rabbitmq_web_stomp.snippets

Fixes #100 
Tested with this file: [rabbitmq.conf.txt](https://github.com/rabbitmq/rabbitmq-web-stomp/files/2668362/rabbitmq.conf.txt)

Add settings to disable TCP and TLS listeners explicitly

---

priv/schema/rabbitmq_web_stomp.schema
test/config_schema_SUITE_data/rabbitmq_web_stomp.snippets

See https://github.com/rabbitmq/rabbitmq-server/issues/1814

Honor cipher suite order in rabbitmq.conf

---

src/rabbit_web_stomp_handler.erl

Ensure that framing error is logged
